"""Refresh final-primary provenance after a source-only audit fix.

This utility does not fit, tune, or evaluate a model.  It preserves each
pre-refresh manifest byte-for-byte, then re-hashes the existing data and model
artifacts against the current clean producing-code tree.  The replacement
manifest explicitly records that the refresh was post hoc and retains the
original manifest timestamp and digest.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from src.config import OUT_MODELS_CONFIGS, OUT_MODELS_SAVED, V2_PROFILE
from src.utils.run_manifest import write_run_manifest


SPEC = V2_PROFILE["spec"]
BACKUP_NAME = "run_manifest_pre_2026_07_22_refresh.json"


def _model_mtimes(saved_dir: Path) -> dict[str, str]:
    return {
        path.name: datetime.fromtimestamp(
            path.stat().st_mtime, timezone.utc
        ).isoformat(timespec="seconds")
        for path in sorted(saved_dir.glob("*.joblib"))
    }


def refresh_one(configs_dir: Path) -> Path:
    manifest_path = configs_dir / "run_manifest.json"
    original_bytes = manifest_path.read_bytes()
    original = json.loads(original_bytes.decode("utf-8"))
    backup_path = configs_dir / BACKUP_NAME

    if not backup_path.exists():
        backup_path.write_bytes(original_bytes)
    else:
        original_bytes = backup_path.read_bytes()
        original = json.loads(original_bytes.decode("utf-8"))

    saved_dir = OUT_MODELS_SAVED / str(original["spec"])
    if not list(saved_dir.glob("*.joblib")):
        raise FileNotFoundError(f"No saved models in {saved_dir}")

    extra = dict(original.get("extra") or {})
    extra.update({
        "provenance_refreshed_posthoc": True,
        "provenance_refresh_reason": (
            "Cumulative post-hoc refresh covering two source-only episodes. "
            "(1) 2026-07-22: audit fixes aligned RC5 fold-safe raw checkpoints "
            "and the verifier's fingerprint scope with the canonical manifest "
            "writer. (2) 2026-07-27: presentation and reporting fixes — the "
            "calibration figure stopped applying a second Platt map on top of "
            "the already-Platt-wrapped saved logistic regression (verified to "
            "reproduce the persisted model's test probabilities exactly, "
            "max|diff| = 0.0), both calibration panels were placed on a shared "
            "probability axis with an inset for the compressed low-risk bins, "
            "Holm correction was moved onto unrounded p-values, and several "
            "docstrings/comments were corrected. NO estimator, Optuna study, "
            "hyperparameter configuration, saved model, or split was refitted "
            "or rewritten in either episode; the frozen data and model digests "
            "are unchanged. Two DERIVED reporting tables were recomputed from "
            "the frozen predictions and did change values: "
            "calibration_comparison_4models (logistic-regression brier_raw is "
            "now the genuine native score, 0.1840, where it previously carried "
            "the calibrated value 0.0150; an ECE column was added) and "
            "significance_tests (Holm-adjusted p-values shifted in the fourth "
            "decimal, moving the logistic-regression-versus-neural-network "
            "PR-AUC comparison across the 5% boundary to an exact 0.04995). "
            "Headline test PR-AUCs are unchanged: 0.1751 / 0.1608 / 0.1729 / "
            "0.1338. "
            "(3) 2026-07-28: source-only hardening after a re-verification of "
            "the 2026-05-04 editorial/code review. Four _selftest guards that "
            "returned True when their frozen reference file was absent now "
            "report NOT VERIFIED (the references had been quarantined to "
            "outputs/_superseded/, so a missing file was a quarantine symptom "
            "being read as a pass), and the two call sites that discarded the "
            "self-test result now raise. _restore_primary_configs raises "
            "instead of warning when the config backup is missing. "
            "src/utils/io.load_model/load_config became spec-aware. Four "
            "superseded drivers (verify_outputs.py, run_pipeline.py, "
            "verify_corrected_outputs.py, regen_significance.py) now abort "
            "unless THESIS_ALLOW_SUPERSEDED_DRIVER=1. build_features.py reads "
            "the CRSP monthly file through DATA_RAW_CRSP instead of a "
            "hand-built relative path (verified to resolve to the identical "
            "directory). attach_filing_dates's default was aligned with its "
            "docstring and with the frozen design (every caller in the tree "
            "already passed the flag explicitly, so no call site changes "
            "behaviour). Comment and docstring corrections in tune.py. NO "
            "estimator, study, config, saved model, split, or derived table "
            "was regenerated in this episode; no reported number changes. "
            "(4) 2026-07-30: independent audit remediation. TWO source files "
            "changed. src/features/market_features.py gained an optional "
            "eligible_segments argument enabling DATE-RANGED restriction of "
            "the market-index and RSIZE denominator; the default path "
            "(eligible_segments=None) is byte-identical in behaviour and is "
            "the path this run used, so no market feature, split, or model is "
            "affected — the date-ranged construction is provided fix-ready and "
            "disclosed, not adopted (measured footprint: 3.83% of index rows, "
            "VWRETD correlation 0.99997, total-market-cap log-ratio 0.00735, "
            "and because RSIZE = log(me) - log(total_me) the error is a "
            "month-common additive shift that leaves within-month "
            "cross-sectional ordering exactly unchanged). "
            "src/robustness/rc3_smote.py fixes a GENUINE DEFECT: the SMOTENC "
            "categorical list contained only OENEG and INTWO while the "
            "final-primary feature set carries a third binary, MB_MISSING, "
            "which was therefore interpolated to fractional values — the exact "
            "failure the corrected mode exists to prevent, and which the "
            "published table caption already (falsely) claimed was prevented. "
            "The list now covers all three binaries and is validated against "
            "the data. CONSEQUENTLY rc3_results and the RC3 rows of "
            "robustness_consolidated WERE REGENERATED and their values change: "
            "PR-AUC 0.1786 -> 0.1739 (LR), 0.1229 -> 0.1235 (RF), 0.1368 -> "
            "0.1317 (XGB), holding the tuned hyperparameters fixed so the "
            "delta is attributable to the fix alone. The RC3 ranking "
            "(LR > XGB > RF) and every substantive conclusion are unchanged. "
            "The superseded RC3 tables are preserved under "
            "outputs/tables/robustness/final_primary/"
            "_superseded_pre_smotenc_binary_fix/. NO estimator, Optuna study, "
            "hyperparameter configuration, saved model, or split was refitted; "
            "the four headline test PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / "
            "0.1338 and saved-model mtimes remain 2026-07-24. "
            "(5) 2026-07-30 (second episode, same day): repo-review remediation. "
            "ONE source file changed, src/analysis/filing_date_selection.py, a "
            "DESCRIPTIVE diagnostic that touches no model, split, feature or "
            "metric. Its matched-versus-unmatched imbalance statistic was "
            "computed as Cohen's d on raw Compustat dollar levels, where pooled "
            "skewness of 17-35 deflates the statistic toward zero: it reported "
            "|d| < 0.10 (balanced) for all eight covariates while matched "
            "firm-years carry ~1.9x the median total assets and ~2.2x the "
            "median sales of unmatched ones. Each covariate is now reported on "
            "three scales (raw levels retained for continuity, log1p, and "
            "scale-free pooled percentile ranks) with the imbalance flag moved "
            "onto the rank version, and three scale-free financial-weakness "
            "covariates were added (ROA, leverage, loss indicator) because a "
            "distress label makes selection on weakness the material question "
            "and dollar levels cannot address it. CONSEQUENTLY the three "
            "filing_date_selection_* descriptive tables WERE REGENERATED; the "
            "overview and by-year tables are unchanged in value, and the "
            "covariate table now flags 7 of 11 covariates as imbalanced where "
            "the levels-only statistic flagged none. NO estimator, Optuna "
            "study, hyperparameter configuration, saved model, split, or "
            "model-results table was regenerated; the four headline test "
            "PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / 0.1338 and saved-model "
            "mtimes remain 2026-07-24. "
            "(6) 2026-08-01: results-validity review. ONE existing source file "
            "changed, src/models/train.py, which gained a forward-looking "
            "runtime guard on repeated test-set evaluation (new module "
            "src/models/evaluation_guard.py): evaluate_on_test now refuses to "
            "re-evaluate an identical (spec, outcome label, horizon, feature "
            "set, test-data hash) tuple unless given a substantive "
            "override_reason, which is recorded in the manifest. The manifest "
            "writer gained six columns and now rewrites on a column union so "
            "legacy rows are preserved un-backfilled rather than misaligned. "
            "The guard is prospective only: the 86 existing manifest rows "
            "carry no evaluation identity, nothing historical is retroactively "
            "blocked, and the disclosed evaluate-once departure stands "
            "unrepaired. All other new code is additive and read-only — an "
            "independent cleaning/preprocessing audit "
            "(src/analysis/cleaning_audit_final_primary.py, 142 checks: 136 "
            "PASS, 6 WARN, 0 FAIL), an artifact-provenance map, and seven "
            "post-hoc supplementary analyses under "
            "outputs/tables/supplementary/final_primary/ (Romano-Wolf and "
            "model-confidence-set ranking inference for H1, operational "
            "precision-at-capacity and expected-cost evaluation, calibration "
            "skill, CCM/CUSIP linkage sensitivity, firm-balanced estimand, "
            "RSIZE denominator sensitivity, and quantitative H4 diagnostics). "
            "The CUSIP sensitivity refits on filtered samples using the frozen "
            "hyperparameters, entirely in memory. Four verified factual "
            "corrections were made to the thesis prose (evaluate-once counts "
            "85/22 -> 86/23; PRICE median censored in seven of nine test years "
            "rather than six; the Chapter 3 CUSIP disposition figures, which "
            "had never been persisted and did not reproduce; and a Chapter 7 "
            "sentence attributing reference-run periods to the primary "
            "specification). NO estimator, Optuna study, hyperparameter "
            "configuration, saved model, split, or primary results table was "
            "regenerated; the four headline test PR-AUCs remain 0.1751 / "
            "0.1608 / 0.1729 / 0.1338, all frozen model and split digests "
            "verify unchanged, and saved-model mtimes remain 2026-07-24. "
            "(7) 2026-08-01 (second episode, same day): documentation only. "
            "The internal design mirror, which was included in the producing "
            "code fingerprint, had its status banner refreshed to match the "
            "2026-08-01 review. Four statements in it were stale or wrong: it "
            "pointed readers to superseded implementation-status sections, "
            "it reported "
            "verification as 203/204 with the code fingerprint as the expected "
            "sole failure (that fingerprint was reconciled on 2026-07-28; the "
            "verifier now passes 204/204), it said 'the trees lead on ROC-AUC' "
            "when only XGBoost's lead over the benchmark survives Holm "
            "(p=.0037) while random forest's does not (p=.103), and it "
            "referred to superseded numbers in '§§1-16 below' when the file's "
            "deviation list stops at item 7. The banner now also carries the "
            "review's positive H1 statement (95% model confidence set retaining "
            "LR, RF and XGBoost; max-statistic test placing the best ML model "
            "0.0022 below the benchmark at p=.73), the evaluate_on_test guard, "
            "and the warning that editing the design mirror breaks this "
            "fingerprint until provenance is refreshed. NO estimator, Optuna "
            "study, hyperparameter configuration, saved model, split, or any "
            "table or figure was touched in this episode; not one reported "
            "number changes. "
            "(8) 2026-08-01 (third episode, same day): CORRECTIVE VALIDATION of "
            "the supplementary inference added in episode (6). An independent "
            "re-audit found that three of those analyses made claims their "
            "procedures did not license. THREE source files changed, all of "
            "them post-hoc supplementary and none of them touching a model, "
            "split, feature, or primary metric. "
            "src/analysis/supp_ranking_inference.py: the Romano-Wolf routine "
            "removed EVERY hypothesis rejected at a step simultaneously instead "
            "of descending the ordering one at a time, so each hypothesis was "
            "judged against a bootstrap maximum taken over a set that still "
            "contained larger statistics — a conservative variant, not the "
            "algorithm the literature defines. It is replaced by the "
            "conventional ordered stepdown (rank by descending |t|, take the "
            "maximum over the current hypothesis and every smaller one, enforce "
            "monotonicity, remove only that hypothesis). Firm-block adjusted "
            "p-values fall uniformly — LR-RF 0.629 -> 0.3595, LR-XGB 0.859 -> "
            "0.8650, LR-NN 0.050 -> 0.0350, RF-XGB 0.148 -> 0.1000, RF-NN 0.148 "
            "-> 0.1000, XGB-NN 0.018 -> 0.0155 — and EVERY substantive rejection "
            "decision is unchanged. The same file's model_confidence_set was "
            "renamed bootstrap_range_model_set (column in_confidence_set -> "
            "in_model_set): it is a range-based adaptation applied to PR-AUC, "
            "which is a rank-based functional of the whole score vector and "
            "admits no additive per-observation loss decomposition, so it is "
            "NOT a Hansen-Lunde-Nason model confidence set and the formal "
            "coverage claim is withdrawn. A formal MCS was deliberately not "
            "substituted, since that would require replacing the primary "
            "estimand with an additive loss. The empirical content is unchanged: "
            "LR/RF/XGB retained in the firm-block set, NN eliminated at p=0.009, "
            "all four retained under firm x year. "
            "src/analysis/supp_h4_nonlinearity.py: the curvature diagnostic "
            "reported a percentile bootstrap interval for the IN-SAMPLE R2 gain "
            "of a spline over a nested linear model and read its exclusion of "
            "zero as evidence of curvature. That gain is the improvement of a "
            "richer nested model over a poorer one on the same data and is "
            "therefore MECHANICALLY NON-NEGATIVE in every resample, so the "
            "interval excludes zero even under a perfectly linear "
            "data-generating process. It is replaced by a firm-cluster wild "
            "bootstrap conducted UNDER THE FITTED LINEAR NULL (Rademacher sign "
            "per firm, 999 replications, knots fixed in advance at the "
            "0.05/0.275/0.5/0.725/0.95 quantiles) plus a firm-grouped 5-fold "
            "out-of-fold gain as an effect size free to go negative; effect size "
            "and p-value are now reported in separate columns and the invalid "
            "interval columns were REMOVED rather than relabelled. The "
            "substantive conclusion survives on the valid basis: a linear "
            "process generates gains whose 95th percentile is 0.0003 / 0.0006 / "
            "0.0005 for TLTA / NITA / SIGMA against observed gains of 0.0479 / "
            "0.3625 / 0.1454, and no replication reaches the observed value "
            "(p=0.001 each). src/analysis/supplementary_common.py gained a "
            "resize flag on write_table so a table with explicit p{} widths is "
            "not additionally rescaled, and src/analysis/supp_estimand_and_drift"
            ".py and src/analysis/filing_date_selection.py gained presentation-"
            "only writers (a two-panel LaTeX layout for the covariate table, "
            "which had been clipped past the right text margin). "
            "CONSEQUENTLY these DERIVED supplementary tables were regenerated: "
            "supp_romano_wolf_pr_auc (adjusted p-values, decisions unchanged), "
            "supp_model_confidence_set (column rename), supp_h1_max_statistic "
            "(verdict string reworded; -0.0022 and p=0.7295/0.7040 unchanged), "
            "supp_h4_nonlinearity (columns replaced), the new supp_h4_segmented, "
            "supp_prevalence_metric_sensitivity, supp_test_prevalence_by_year, "
            "and filing_date_selection_covariates (LAYOUT ONLY — every value "
            "reproduces identically and the CSV is unchanged). "
            "NO estimator, Optuna study, hyperparameter configuration, saved "
            "model, split, or primary results table was regenerated; the four "
            "headline test PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / 0.1338, "
            "H1 remains not supported and metric-dependent, and saved-model "
            "mtimes remain 2026-07-24. H4's reported verdict changes from "
            "supported-on-curvature to PARTIALLY SUPPORTED, which is a "
            "conclusion about the pre-registered hypothesis and not a change to "
            "any estimate; the hypothesis text itself is untouched. "
            "(9) 2026-08-03: PRESENTATION ONLY. write_table in "
            "src/analysis/supplementary_common.py now wraps supplementary "
            "tabulars in \\adjustbox{max width=\\textwidth} instead of "
            "\\resizebox{\\textwidth}{!}. \\resizebox forces a tabular to "
            "exactly the text width in both directions, so a narrow three- or "
            "four-column table was scaled UP and typeset at roughly twice body "
            "size; max width shrinks only what is genuinely too wide and leaves "
            "everything else at its natural size. supp_estimand_and_drift.py "
            "dropped a now-redundant resize=False that had been a workaround "
            "for the same defect. ALL SIX supplementary generators were re-run "
            "(supp_ranking_inference, supp_estimand_and_drift, "
            "supp_rsize_denominator, supp_economic_calibration, "
            "supp_h4_nonlinearity, supp_cusip_linkage_sensitivity), "
            "regenerating all 18 supplementary tables. EVERY ONE OF THE 18 "
            "CSVs IS BYTE-IDENTICAL to its pre-run snapshot, including "
            "supp_cusip_linkage_sensitivity, whose in-memory refit on filtered "
            "splits under frozen hyperparameters reproduced exactly. Only the "
            "LaTeX wrapper line changed in the .tex files. NO estimator, Optuna "
            "study, hyperparameter configuration, saved model, split, or "
            "reported value was altered; the four headline test PR-AUCs remain "
            "0.1751 / 0.1608 / 0.1729 / 0.1338 and saved-model mtimes remain "
            "2026-07-24. "
            "(10) 2026-08-03: authoring utility only. ONE new source file, "
            "scripts/memo_md_to_docx.py, which renders a project decision "
            "memo from Markdown to Word so successive memo versions stop "
            "drifting in formatting. It reads no data, loads no model, and "
            "writes nothing under outputs/. It enters the code fingerprint "
            "solely because the fingerprint hashes every .py file under "
            "scripts/. Committed alongside a thesis prose fix: the status box "
            "heading the post-hoc supplementary section claimed 'None of it "
            "revises H1-H4', which stopped being true when the H4 verdict moved "
            "to partially supported in episode (8) — that section is precisely "
            "what revises it. NO estimator, Optuna study, hyperparameter "
            "configuration, saved model, split, table, figure or reported "
            "number was touched; the four headline test PR-AUCs remain "
            "0.1751 / 0.1608 / 0.1729 / 0.1338 and saved-model mtimes remain "
            "2026-07-24. "
            "(11) 2026-08-04: repo-review remediation of the winsorisation "
            "convention. THREE source files, one of them new, none touching a "
            "model, split, feature or primary metric. The review established "
            "that the 1st/99th-percentile bounds, fitted on 1990-2008 and "
            "correctly applied unchanged thereafter, censor far more of the "
            "EVALUATION sample than the nominal 1%: 4.24% of test firm-years "
            "for CASHTA in the upper tail, 3.56% LNMK, 3.25% LNTA, 2.87% WCTA, "
            "with 11 of the 14 winsorised predictors above 2% in at least one "
            "test tail. This is the correct leakage-free rule meeting a "
            "non-stationary panel, not a defect, but it was undisclosed and "
            "the audit could not surface it. "
            "src/analysis/cleaning_audit_final_primary.py: the winsorisation "
            "check reported clipped cells as ONE pooled share of (rows x 14 "
            "features) per split, which diluted a 4% single-feature rate below "
            "visibility and was hard-coded PASS with no threshold — it could "
            "not fail. It now reports the realised rate PER FEATURE against the "
            "raw value, with a 2% per-tail trigger (WINSOR_DRIFT_PCT), and "
            "correctly WARNs on validation and test while training passes. The "
            "comparison was also made STRICT so that only values genuinely "
            "altered count: CHIN's percentiles are exactly its natural bounds "
            "(-1, +1), where a fifth of the panel sits because Ohlson's ratio "
            "saturates on a net-income sign change, and the previous non-strict "
            "test would have reported that mass point as 21% censoring. The "
            "same file's claim that the excluded set is '4 bounded/binary' was "
            "corrected: PRICE is capped ABOVE only. "
            "src/features/winsorize.py: comment only. NO_WINSORISE carried the "
            "justification 'already bounded; PRICE is capped at log(15)', which "
            "described a one-sided cap as two-sided boundedness. PRICE's left "
            "tail is unbounded, reaching -5.9 training standard deviations. The "
            "exclusion is RETAINED and the comment now records the measured "
            "ground for retaining it: 36 of the 404 test events lie in the "
            "0.89% of test rows below the training 1st percentile (15.9% "
            "distress rate against 1.58% overall), and winsorising PRICE moves "
            "test PR-AUC by -0.0008 / -0.0018 / -0.0023 / -0.0216 — every model "
            "weakly worse, ranking unchanged. "
            "src/analysis/supp_winsorisation_convention.py (NEW): the "
            "re-runnable generator backing both disclosures, so no thesis "
            "number rests on an ad-hoc script. It rebuilds all three splits "
            "from the raw checkpoints under four winsorisation regimes and "
            "refits on the FROZEN hyperparameters. Its control asserts, before "
            "writing anything, that the rebuild reproduces the stored splits to "
            "machine precision (max |diff| = 0.0 across all 18 features and all "
            "three splits, exact row counts) AND reproduces the published "
            "PR-AUCs exactly. Finding: per-fiscal-year cross-sectional "
            "winsorisation — point-in-time legitimate but a DEVIATION from the "
            "frozen design, reported as a sensitivity and NOT adopted — moves "
            "the benchmark to 0.1611 against XGBoost's 0.1683, so the reported "
            "point first place changes hands. That is the THIRD perturbation to "
            "reorder the top three, alongside the fresh search of episode-era "
            "sec:rc_corrected_retune (leader turns on 0.0006) and the "
            "firm-balanced estimand, and it is consistent with the bootstrap "
            "model set that already declines to order them. TWO NEW derived "
            "supplementary tables were written "
            "(supp_winsorisation_realised_censoring, "
            "supp_winsorisation_convention_sensitivity) and the two "
            "cleaning-audit CSVs were regenerated: the audit total is unchanged "
            "at 142 checks but now reads 134 PASS / 8 WARN / 0 FAIL, the two new "
            "WARNs being the val and test censoring rates the previous pooled "
            "statistic concealed. NO estimator, Optuna study, hyperparameter "
            "configuration, saved model or split was refitted or rewritten; the "
            "four headline test PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / "
            "0.1338 and saved-model mtimes remain 2026-07-24. "
            "(12) 2026-08-04 (second episode, same day): a third-party review "
            "was cross-checked against the artifacts and code, and the H2 "
            "training-side design was found NULL BY CONSTRUCTION. THREE source "
            "files, two of them new, none touching a model, split, feature or "
            "primary metric. "
            "src/analysis/h2_leakage_sensitivity.chronological_test_"
            "contaminated_train defines the test block as EVERY firm-year "
            "after VAL_END_YEAR and then draws the training pool from firms "
            "ABSENT from that block, so a firm owning any post-2014 row is "
            "excluded entirely and the pool cannot contain a post-2014 row. "
            "Measured: 0 post-2014 rows under all five seeds. Its near-zero "
            "delta_pr_leaky_train was therefore mechanically guaranteed, not "
            "measured, and the mechanism claim that rested on it — that "
            "time-contaminated training per se adds essentially nothing — has "
            "been WITHDRAWN from ch01, ch02 and ch06. The module itself is left "
            "unmodified so the superseded table remains reproducible. "
            "src/analysis/supp_h2_training_channel.py (NEW) replaces it with a "
            "design that can carry the question: the post-2014 period is split "
            "in time, giving a fixed FY2015-2019 evaluation block (13,583 "
            "firm-years, 179 events) and an FY2020-2023 future block lying "
            "entirely after it, so training on the latter is genuine "
            "future-information contamination. Five arms add nothing, the whole "
            "future block, its rows from never-evaluated firms only, 2,674 "
            "future rows, and 2,674 recent-past (FY2010-2014) rows — the last "
            "pair size-matched so the effect of future information is separated "
            "from the effect of simply having more training data, a control the "
            "predecessor lacked entirely. Default hyperparameters throughout, as "
            "in the main split-design experiment; contrasts use the headline "
            "firm-block paired bootstrap. Validation: the baseline arm "
            "reproduces the TUNED models' FY2015-2019 subperiod PR-AUCs to "
            "within 0.0015 with identical ordering. Finding: the total "
            "training-side effect is +0.0027 / +0.0066 / +0.0097 (LR/RF/XGB), "
            "every interval containing zero, and at equal added row count "
            "future data does not beat recent-past data (-0.0004 / +0.0012 / "
            "+0.0077, p = .54 / .67 / .33), against an evaluation-side channel "
            "of +0.043 to +0.084. The withdrawn conclusion is thus supported "
            "after all, but is now stated as a BOUND rather than an absence "
            "(179 events; all point estimates positive). Reproduced "
            "byte-identically across three independent runs. "
            "src/analysis/supp_h3_statistic_choice.py (NEW) demonstrates, "
            "rather than asserts, why the implemented H3 directional statistic "
            "departs from the frozen wording: in a 98.4%-non-distress sample "
            "the mean SHAP attribution is negative for ALL TEN leading "
            "features, so the literal rule would score 7/10, recording "
            "Inconsistent for exactly the three features whose pre-registered "
            "prediction is positive (TLTA, SIGMA, CLCA) despite feature-SHAP "
            "correlations of +0.901, +0.819 and +0.763. The substitution is "
            "necessary for the test to carry content, not a relaxation of it. "
            "src/analysis/supp_economic_calibration.py: caption only — the "
            "operational-capacity table now records that its precision column "
            "is NOT comparable across models within a capacity row, each model "
            "realising a different test capacity (2.98% to 5.44%) at its own "
            "validation quantile. THREE NEW derived supplementary tables were "
            "written (supp_h2_training_channel, its contrasts, "
            "supp_h3_statistic_choice) with full-detail CSVs archived beside "
            "them; the four regenerated economic-calibration CSVs are "
            "byte-identical to their pre-run snapshots. NO estimator, Optuna "
            "study, hyperparameter configuration, saved model or split was "
            "refitted or rewritten, evaluation_manifest.csv remains at 86 rows "
            "(the new experiment uses compute_all_metrics, not the guarded "
            "evaluate_on_test), the four headline test PR-AUCs remain 0.1751 / "
            "0.1608 / 0.1729 / 0.1338 and saved-model mtimes remain 2026-07-24. "
            "(13) 2026-08-04/05: the two outstanding compute-bearing robustness "
            "gaps were closed. FOUR new source files, none touching a primary "
            "estimator, split, feature or metric. "
            "(a) RC3 RE-TUNE. src/robustness/rc3_smote_retune.py and "
            "scripts/run_rc3_retune.py run a genuine 100-trial Optuna search "
            "per model under SMOTENC, closing the one protocol asymmetry inside "
            "the pre-specified set (RC1/RC2/RC4/RC5 re-tune; RC3 had reused the "
            "primary configurations, which confounds the imbalance method with "
            "hyperparameter compatibility). Tuned configs live in a SEPARATE "
            "spec namespace, outputs/models/configs/final_primary_rc3/, so a "
            "re-tune structurally cannot overwrite the primary configs. Within "
            "the search, standardisation and SMOTENC are fitted on each fold's "
            "TRAINING rows only and validation rows are never resampled, so no "
            "synthetic minority point is built from an observation used to "
            "score the fold; verified in a smoke test where validation folds "
            "retained their original event counts (62/32/35/118/106, matching "
            "the primary CV folds) while fold-training roughly doubled. The "
            "final fit and single test evaluation are DELEGATED to the existing "
            "run_rc3(corrected=True, params_dir=...), so the evaluated pipeline "
            "is the already-audited one rather than a second implementation. "
            "Result: re-tuning helps every model slightly and changes nothing "
            "material -- PR-AUC LR .1739->.1762, RF .1235->.1293, XGB "
            ".1317->.1356, ordering unchanged. Against the primary "
            "class-weighted specification SMOTE costs RF 0.0315 and XGB 0.0373 "
            "while costing LR nothing (+0.0011), so the RC3 finding was never "
            "driven by hyperparameter mismatch and now stands unqualified. The "
            "search is genuine, not a formality: LR's ridge penalty moves C "
            "1.168 -> 0.0117. The frozen rc3_results table is NOT overwritten; "
            "rc3_retuned_results.{csv,tex} is NEW and ch07 reports both. "
            "(b) NN ROBUSTNESS BATTERY. src/robustness/rc_nn_final_primary.py "
            "and scripts/run_rc_nn_final_primary.py run the balanced network "
            "through primary + RC1-RC5, closing the gap in which one of the "
            "four co-primary models had no current robustness evidence (its "
            "NN-across-checks artifacts belong to superseded generations). "
            "Hyperparameters are FROZEN at the primary specification's and the "
            "network is refit per check -- the supplementary convention of "
            "chapter 7, not the per-check re-tune the other three receive, a "
            "per-check search for this model being a 1-3 day computation; the "
            "asymmetry is bounded by (a)'s measured re-tune gains against the "
            "network's 0.027 deficit. Every check's label, horizon, predictor "
            "set and sample are constructed with the SAME calls the other "
            "models use and all six reproduce the published baselines exactly. "
            "RC3's analogue for this model is SMOTENC replacing "
            "oversampling-to-parity, built as run_rc3 builds it. The primary "
            "row reproduces the headline exactly (.1338, ROC .9140); the "
            "network places 4th of 4 in five of six checks and 3rd only in the "
            "~69-event RC1. ONE NEW derived table, "
            "rc_nn_final_primary_results.{csv,tex}. "
            "NO estimator, Optuna study, hyperparameter configuration, saved "
            "model or split of the PRIMARY specification was refitted or "
            "rewritten in either part; both fit only in-memory models, RC3's "
            "under its own spec namespace; evaluation_manifest.csv is "
            "unchanged; the four headline test PR-AUCs remain 0.1751 / 0.1608 "
            "/ 0.1729 / 0.1338 and saved-model mtimes remain 2026-07-24. "
            "(14) 2026-08-05/07: per-check hyperparameter search for the "
            "balanced neural network across RC1-RC5, removing the last protocol "
            "asymmetry in chapter 7. THREE source files, two of them new, plus "
            "one test file; none touches a primary estimator, split, feature or "
            "metric. src/robustness/rc_nn_retune.py and "
            "scripts/run_rc_nn_retune.py run 100 Optuna trials per check on the "
            "same fold-safe rolling-origin folds used by LR/RF/XGBoost and by "
            "the primary network's own search, with per-check checkpointing and "
            "persistent per-check Optuna storage; tuned configurations live in "
            "one spec namespace per check "
            "(outputs/models/configs/final_primary_rc{1..5}_nn/) so no search "
            "can overwrite another's or the primary's. "
            "src/robustness/rc_nn_final_primary.py gained get_check_raw_train: "
            "fold-safe CV consumes the RAW training frame, so RC1 and RC2 must "
            "re-label it before folds are built, otherwise every search would "
            "optimise against the PRIMARY label and be scored on a re-labelled "
            "test set -- a silent failure of the same class as the withdrawn H2 "
            "design. Verified: RC1 fold frame 242 events, RC2 1,165, primary "
            "2,244; guarded by tests/test_rc_nn_retune_relabel.py. "
            "RESULT (network PR-AUC, frozen -> re-tuned): RC1 .0317 -> .0301, "
            "RC2 .0613 -> .0674, RC3 .1116 -> .1492, RC4 .1156 -> .1133, RC5 "
            ".1259 -> .1185. Four of five move by less than 0.008 and reorder "
            "nothing, three of those four negatively. RC3 is the sole exception "
            "and the only reordering: +0.0376, and the network moves from "
            "fourth to second, re-tuned RC3 reading LR .1762 > NN .1492 > XGB "
            ".1356 > RF .1293. This FALSIFIES the bounding argument previously "
            "in ch07 sec:rc_nn, which is withdrawn. Mechanism: RC3 is the one "
            "check that changes the imbalance treatment, and the network's "
            "primary hyperparameters were selected under oversampling-to-parity, "
            "so it is the one check whose design removes the training regime "
            "those settings were chosen for. "
            "Disclosed caveat: the searches were interrupted and resumed "
            "(session teardown twice), so the TPE sampler conditioned on stored "
            "trials rather than one uninterrupted sequence; all 100 trials per "
            "check are valid evaluations of the same objective, but a "
            "from-scratch re-run would explore a different sequence. The same "
            "already applies to the primary network. RC4 was audited after its "
            "interruption: 100 COMPLETE, 0 FAIL, config identical to the study "
            "best, and its test result reproduces exactly on an independent "
            "refit (.1133 / .8932 / .1920). "
            "ONE NEW derived table, rc_nn_retuned_results.{csv,tex}; ch07 "
            "sec:rc_nn rewritten with a new comparison table beside the frozen "
            "one; ch08's H1 paragraph qualified; ch07's RC2 ratio corrected "
            "0.62 -> 0.61. NO estimator, Optuna study, hyperparameter "
            "configuration, saved model or split of the PRIMARY specification "
            "was refitted or rewritten; every fit is in-memory under a "
            "check-specific namespace; evaluation_manifest.csv is unchanged; "
            "the four headline test PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / "
            "0.1338 and saved-model mtimes remain 2026-07-24. "
            "(15) 2026-08-07: PRESENTATION ONLY — figure typography. THREE "
            "source files changed, none of which touches a model, split, "
            "feature, label or metric. src/utils/fig_style.py set "
            "font.family='sans-serif' (DejaVu Sans) with semibold titles and a "
            "background grid while its own docstring documented serif/STIX "
            "typography matching the LaTeX body text; the code now matches its "
            "documented intent — serif (STIXGeneral, DejaVu Serif fallback), "
            "mathtext stix, regular-weight titles, grid off — restoring the "
            "sober register of the pre-consistency-pass figures. STIXGeneral "
            "was chosen over matplotlib's bundled cmr10, the closer metric "
            "match to lmodern, because cmr10 carries no en/em dash and no "
            "U+2212 minus and would render those as missing glyphs. The "
            "colorblind-safe Okabe-Ito palette and the redundant "
            "line/marker encodings from the Phase A reporting fixes are "
            "UNCHANGED. scripts/run_v2_xai.py: the three LIME panels had "
            "regressed to lime's as_pyplot_figure default, whose saturated "
            "green/red is both outside the thesis palette and the one pairing "
            "deuteranopes cannot separate; they are now drawn directly with "
            "signed thesis colours and a direction-cued axis label. The three "
            "SHAP waterfalls and three LIME panels are typeset three-up at "
            "0.47\\textwidth, i.e. 2.87 in on the page against a 7 in canvas, "
            "so the 9 pt figure font printed below 4 pt; their type is now "
            "scaled 2.2x on the unchanged canvas (SHAP's internal row layout "
            "left intact) to print at roughly 8 pt. The annual-distress-rate "
            "legend no longer overlaps the FY2000-01 peak. src/utils/tables.py "
            "gained optional column_labels and column_format arguments to "
            "save_table, applied to the LaTeX output only so CSVs keep "
            "machine-readable names; local_explanation_cases.tex had carried "
            "hand-edited readable headers that no code could reproduce and now "
            "regenerates character-identical from the generator. Two captions "
            "were corrected: lev_roa_interaction_contrast still asserted "
            "'genuine super-additivity', a claim withdrawn in the 2026-08-01 "
            "review after the SHAP interaction estimator failed to corroborate "
            "it, and calibration_comparison_4models now names Platt (sigmoid) "
            "scaling. ALL 20 thesis figure targets were regenerated by scoring "
            "the frozen .joblib models; every value reproduced exactly (LIME "
            "Kendall tau .378 / .022 / .511, local cases 186061 / 26382 / "
            "12445, leverage-profitability corner contrast +0.084). NO "
            "estimator, Optuna study, hyperparameter configuration, saved "
            "model, split, or numeric table cell was regenerated or changed; "
            "evaluation_manifest.csv is unchanged; the four headline test "
            "PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / 0.1338 and saved-model "
            "mtimes remain 2026-07-24. "
            "(16) 2026-08-07 (second episode, same day): PRESENTATION ONLY — "
            "figure text. TWO source files changed, neither touching a model, "
            "split, feature, label or metric. scripts/run_v2_secondary.py "
            "carried three consecutive set_title calls on the precision-recall "
            "axes and two on the ROC axes; the surviving precision-recall "
            "title spelled the term with a HYPHEN, silently overwriting the "
            "correct en dash set on the line immediately above, so the "
            "published figure carried the wrong dash. In-figure titles were "
            "then removed from all seven single-panel targets that already "
            "carry a full LaTeX caption (ROC, precision-recall, calibration, "
            "annual distress rate, SHAP beeswarm, SHAP mean-absolute bar, "
            "leverage-profitability heatmap): each caption already names its "
            "model and its sample, so the titles were pure duplication. For "
            "the heatmap the variable names the removed title carried "
            "('leverage (TLTA)', 'profitability (NITA)') were moved onto the "
            "axis labels and the tertile ticks reduced to Low/Mid/High, so the "
            "panel stays self-describing. The three SHAP waterfalls and three "
            "LIME panels are typeset three-up under a single caption and so "
            "keep a panel label, now spelled out ('True positive', 'False "
            "negative', 'True negative') rather than the script tags TP/FN/TN. "
            "LIME discretisation rules are typeset for print: '<=' and '>=' "
            "become U+2264/U+2265 and a hyphen-minus preceding a numeral "
            "becomes U+2212, so 'RSIZE <= -12.52' now prints as 'RSIZE ≤ "
            "−12.52'; feature names carry underscores but never hyphens, so "
            "keying the minus on a following digit cannot corrupt a name, and "
            "STIXGeneral was confirmed to carry all four glyphs BEFORE "
            "regenerating (the cmr10 failure mode recorded in episode 15). "
            "Only the label text changes — rule, threshold and weight are "
            "untouched. The LIME x-axis label lost its stray double space and "
            "its arrow glyph. A first attempt, '(positive raises predicted "
            "risk)', measured 6.08 in against a 7 in canvas and, because the "
            "axes sit right of centre behind the wide rule tick labels, "
            "printed FLUSH against the saved bbox with the closing bracket cut "
            "off; it was shortened to '(positive raises risk)' at 4.87 in, "
            "matching the 4.88 in label it replaced, and the restored right "
            "margin was then measured at 27-31 px on all three panels. ALL 20 "
            "thesis figure targets were regenerated by scoring the frozen "
            ".joblib models. Every derived table was byte-diffed against a "
            "pre-run snapshot and NOT ONE table file changed. NO estimator, "
            "Optuna study, hyperparameter configuration, saved model, split, "
            "or numeric table cell was regenerated or changed; "
            "evaluation_manifest.csv is unchanged; the four headline test "
            "PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / 0.1338 and saved-model "
            "mtimes remain 2026-07-24. "
            "(17) 2026-08-07 (third episode, same day): PRESENTATION ONLY — "
            "figure layout, on the author's judgement that three exhibits did "
            "not read as academic. TWO source files changed. FIRST, three "
            "layout defects were corrected. The CALIBRATION panel ran its axes "
            "to the maximum calibrated score (~0.35) while the highest "
            "reliability bin sits near 0.19, so about two thirds of the panel "
            "was empty and the curves were compressed into one corner; the "
            "shared axis is now set by the reliability points (0.200). This "
            "CLIPS 3,911 of 102,048 model-observation scores (3.833%) out of "
            "the lower distribution panel — all ten bins of every reliability "
            "curve are still shown, and the ch07 caption, which previously "
            "asserted that no observation is clipped, now states the cap and "
            "the count. Cropping moved the curves into the space the detail "
            "inset had occupied, so the inset moved to the empty triangle "
            "above the diagonal and the legend to the vacated lower right. "
            "SECOND, the ANNUAL DISTRESS RATE figure shaded its three split "
            "periods at alpha 0.035, which renders as bare white: the bands "
            "were invisible and their legend swatches were empty boxes. The "
            "bands are now drawn at alpha 0.10 and each is labelled in place, "
            "which removes the legend entirely (there is one series). THIRD, "
            "the CORRELATION MATRIX moved from a triangular layout that named "
            "each predictor once on a leader off its own diagonal cell to the "
            "conventional full square with names down the left edge and along "
            "the bottom, plus a colour ramp labelled 'Pearson r'; the ch04 "
            "caption, which taught the old diagonal reading rule, was rewritten. "
            "Also in this episode: the two generated case tables "
            "(local_explanation_cases, lime_shap_agreement) now spell their "
            "``case`` column out as True positive / False negative / True "
            "negative instead of the tags TP/FN/TN, matching the figures — a "
            "LABEL change to two table columns, verified against both "
            "verifiers, which assert only the row count and key on no "
            "abbreviation; and lime_shap_agreement gained column_labels so its "
            "printed headers are no longer the raw snake_case names (LaTeX "
            "only; the CSV keeps machine-readable names). NOTE the author "
            "supplied five v1 figures as a style reference; the STYLE cues "
            "were adopted but the figures were NOT, because they belong to the "
            "superseded generation (17 predictors, FY1990-2024, v1 ECE and "
            "PR-AUC values) that outputs/_superseded/README.md marks DO NOT "
            "CITE. NO estimator, Optuna study, hyperparameter configuration, "
            "saved model, split, or NUMERIC table cell was regenerated or "
            "changed; evaluation_manifest.csv is unchanged; the four headline "
            "test PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / 0.1338 and "
            "saved-model mtimes remain 2026-07-24. "
            "(18) 2026-08-08: PRESENTATION ONLY — figure register changed on "
            "the author's selection. Three candidate styles were rendered side "
            "by side from the reported numbers and the author chose the "
            "information-systems/report register, so src/utils/fig_style.py now "
            "sets DejaVu Sans at 11.5 pt base, a full background grid, boxed "
            "axes and a framed legend. TWO CONSEQUENCES ARE DISCLOSED RATHER "
            "THAN HIDDEN. (a) The model palette moves from Okabe-Ito to tab10 "
            "blue/orange/green/red; adjacent tab10 pairs are harder to separate "
            "under deuteranopia than the Okabe-Ito set introduced by the Phase "
            "A reporting fixes. The accessibility cost was put to the author "
            "before the change. The MITIGATION is that colour is never the sole "
            "carrier of model identity: MODEL_LINESTYLES and MODEL_MARKERS are "
            "retained unchanged, so every series stays identifiable in "
            "greyscale and under any colour-vision deficiency. (b) The type is "
            "sans-serif and therefore no longer matches the Latin Modern body "
            "text, reversing the intent of episode 15; this too was the "
            "author's choice among the rendered candidates, in exchange for "
            "larger and more legible type. IN-FIGURE TITLES ARE REINSTATED, "
            "centred, reversing episodes 16 and 17 on the author's explicit "
            "instruction; each is written in the academic register and carries "
            "the CORRECT final_primary facts (18 inputs, FY1990-2023 modelling "
            "sample, FY2015-2023 test sample), never the superseded v1 wording. "
            "Each figure now states its subject twice, in the title and again "
            "in its LaTeX caption; that duplication is intended. THE "
            "CORRELATION MATRIX moved from a hand-emitted TikZ picture to a "
            "matplotlib figure, so it inherits the shared style module instead "
            "of being kept consistent by hand; ch04 switched from \\input to "
            "\\includegraphics and the TikZ source was retired. Finally, the "
            "\"(balanced)\" qualifier was removed from the neural-network label "
            "in figures, generated tables AND prose together (19 sites across "
            "ch01, ch05, ch06, ch07 and ch08), on the author's instruction. It "
            "is unambiguous because final_primary contains no raw neural "
            "network; the sentences where the qualifier carried methodological "
            "content -- that this network receives minority oversampling, and "
            "that it is the imbalance-matched specification -- were preserved "
            "and reworded rather than deleted. THREE generated tables therefore "
            "change one LABEL cell each (calibration_comparison_4models, "
            "model_performance_test_4models, significance_tests); both "
            "verifiers assert only row counts and key on no abbreviation. NO "
            "estimator, Optuna study, hyperparameter configuration, saved "
            "model, split, or NUMERIC table cell was regenerated or changed; "
            "evaluation_manifest.csv is unchanged; the four headline test "
            "PR-AUCs remain 0.1751 / 0.1608 / 0.1729 / 0.1338 and saved-model "
            "mtimes remain 2026-07-24."
        ),
        "original_manifest_timestamp_utc": original.get("timestamp_utc"),
        "original_manifest_sha256": hashlib.sha256(original_bytes).hexdigest(),
        "saved_model_mtime_utc": _model_mtimes(saved_dir),
        "preserved_original_manifest": BACKUP_NAME,
    })

    return write_run_manifest(
        configs_dir=configs_dir,
        saved_dir=saved_dir,
        spec=str(original["spec"]),
        features=list(original["features"]),
        samples_dir=Path(original["data_dir"]),
        input_files=[Path(path) for path in original.get("input_files", {})],
        extra=extra,
    )


def main() -> None:
    manifests = sorted(
        OUT_MODELS_CONFIGS.glob(f"{SPEC}*/run_manifest.json"),
        key=lambda path: str(path).lower(),
    )
    if not manifests:
        raise FileNotFoundError(f"No {SPEC} manifests found")
    for manifest_path in manifests:
        refreshed = refresh_one(manifest_path.parent)
        print(f"  Refreshed provenance only: {refreshed}")


if __name__ == "__main__":
    main()
